server:
  port: 9090

spring:
  application:
    name: 02-配置管理
profiles:
  active: dev

app:
  name: 配置管理模块
  author: ${yixz.name}
  port: 9090
  max-count: 100

yixz:
  name: 张心怡
  job: 学生

student:
  name: 张大三
  age: 23
  hobbies:
    - 唱歌
    - 编程
    - 跳舞
  scores:
    chinese: 90
    math: 95
    english: 98
  address:
    province: 江苏省
    city: 无锡
  courses:
    - name: 高等数学
      credit: 4
    - name: 大学英语
      credit: 3


